flinkmaster:
    image: bde2020/flink-master:latest
    hostname: flink-master
    environment:
      - INIT_DAEMON_STEP=setup_flink
flinkworker:
    image: bde2020/flink-worker:latest
    hostname: flink-worker
    links:
      - "flinkmaster:flink-master"

